version: 0.3.4.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore

build:
  project: ReDock.sln
  verbosity: minimal

after_test:
 - ps: .\nuget\pack.ps1

artifacts:
- path: ReDock.*.nupkg
  name: redock


deploy:
- provider: NuGet
  api_key:
    secure: 15QfONSEfo0p8Y0WsN43Lp06VHkaB4CfOaTS9uWlR0NH6QfC2HHN5BfQUT0uzC+l
  skip_symbols: false
  on:
    branch: master
