version: 0.4.4

configuration:
- Release

branches:
  only:
    - master

# assembly_info:
#   patch: true
#   file: AssemblyInfo.*
#   assembly_version: "{version}"
#   assembly_file_version: "{version}"
#   assembly_informational_version: "{version}"
  
install: 
- ps: .\build.ps1 

build_script:
- dotnet restore 
- dotnet build "src\ReDock" -c release
- dotnet pack "src\ReDock" -c release -o ./

artifacts:
- path: ReDock.*.nupkg
  name: redock

deploy:
- provider: NuGet
  api_key:
    secure: 15QfONSEfo0p8Y0WsN43Lp06VHkaB4CfOaTS9uWlR0NH6QfC2HHN5BfQUT0uzC+l
  skip_symbols: false
  on:
    branch: master
